name: Call Reusable Workflow1

on:
  [push]

jobs:
  run-template:
    uses: neilmca-inc/test-template/.github/workflows/template.yml@v1.0.2
    #with:
    #  example-input: 'Hello, world!'
    #secrets:
    #  EXAMPLE_SECRET: ${{ secrets.EXAMPLE_SECRET }}