name: GitHub Actions Repo Vars and Secrets
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: 
  [push]

jobs:
  Explore-GitHub-Actions-Var-Secrets:
    runs-on: ubuntu-latest
    steps:
      - name: one
        run: echo "Repo Secret REPO_SECRET_MINOGUE: ${{ secret.REPO_SECRET_MINOGUE }}"
      - name: two
        run: echo "Repo Variable REPO_VAR_MINOGUE: ${{ vars.REPO_VAR_MINOGUE }}"     

        