name: GitHub Actions Repo Vars and Secrets
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: 
  #[push]
  pull_request:
    branches: [ "main" ]

jobs:
  Explore-GitHub-Actions-Var-Secrets:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Repo Secret ${{ secrets.REPO_SECRET_MINOGUE }}"
      - run: echo "Repo Variable ${{ vars.REPO_VAR_MINOGUE }}"     

        